
package jdbc_lab;

//import com.mysql.cj.x.protobuf.MysqlxCrud.Update;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UR SYSTEM ADMIN
 */
public class JDBC_UI extends javax.swing.JFrame {

    /**
     * Creates new form JDBC_UI
     */
    public JDBC_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setFont(new java.awt.Font("Agency FB", 2, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("CRUD APPLICATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 11, 237, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 106, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 106, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Reg No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, 106, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 92, 149, 33));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 143, 149, 31));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 185, 149, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 97, 34));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 97, 34));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("INSERT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 97, 34));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("save updates");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 130, 34));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("VIEW DATA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 110, 35));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRST NAME", "LAST NAME", "REG  NUMBER"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  String conString = "jdbc:mysql://localhost:3306/users";
    String username = "root";
    String password = "";
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
model.setRowCount(0);
show_Data();
     
           try {
               //GET COONECTION
               Connection con=DriverManager.getConnection(conString, username, password);
               
               String fname=jTextField1.getText();
                String lname=jTextField2.getText();
                 String regNo=jTextField3.getText();
                
        if(fname.length()==0 || lname.length()==0 || regNo.length()==0){
              JOptionPane.showMessageDialog(this, "PLEASE FILL ALL FIELDS", "Error", JOptionPane.ERROR_MESSAGE);
          }  else{       
                 String sql = "INSERT INTO users VALUES('" + fname + "','" +lname + "','" + regNo+ "')";
               Statement s = con.prepareStatement(sql);

            s.execute(sql);
            
             jTextField1.setText("");
               jTextField2.setText("");
                 jTextField3.setText("");
        JOptionPane.showMessageDialog(this, "DATA INSERTED SUCCESFULLY");
                

model.setRowCount(0);
show_Data();


        }
        
           } catch (SQLException ex) {
               Logger.getLogger(JDBC_UI.class.getName()).log(Level.SEVERE, null, ex);
           }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try{
         
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/users","root","");
         DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
          int row = jTable1.getSelectedRow();
          if(jTable1.getSelectedRowCount()>0)
          {
              String key=(String) md.getValueAt(row,2);
         // int key=Integer.parseInt(md.getValueAt(row,2).toString());
          String delete="delete from users where regNo="+key;
          PreparedStatement del=con.prepareStatement(delete);
          del.executeUpdate();
             DefaultTableModel tabm=(DefaultTableModel)jTable1.getModel(); 
             tabm.setRowCount(0);
             show_Data();
           JOptionPane.showMessageDialog(this, "Data Deleted succesfully", "success", JOptionPane.INFORMATION_MESSAGE);
        }
        else
          {
            JOptionPane.showMessageDialog(this, "Select a row to be Deleted", "Error", JOptionPane.ERROR_MESSAGE);  
          }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed
//updating function
    
     public Boolean update( String fname, String lname, String regNo) {
          jTextField1.setText(fname);
          jTextField2.setText(lname);
          jTextField3.setText(regNo);
          
          String m=jTextField1.getText();
          String n=jTextField2.getText();
          String o=jTextField3.getText();
        //SQL STMT
        
       String sql="delete from users where regNo="+regNo;
       
       
        //String sql = "UPDATE student SET fname ='" + m + "',lname='" + n + "',regNo='" + o + "' WHERE regNo='" + o+ "'";

        try {
            //GET COONECTION
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost/users","root","");

            //STATEMENT
            Statement s = con.prepareStatement(sql);

            //EXECUTE
            s.execute(sql);
  
            return true;

        } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
        int row2 = jTable1.getSelectedRow();
        if(jTable1.getSelectedRowCount()>0){
       
          String fname=md.getValueAt(row2,0).toString();
          String lname=md.getValueAt(row2,1).toString();
          String regNo=md.getValueAt(row2,2).toString();
          jTextField1.setText(fname);
          jTextField2.setText(lname);
          jTextField1.setText(regNo);
      update(fname, lname, regNo);
        }
        else
        {
         JOptionPane.showMessageDialog(this, "Select a row to be Updated", "Error", JOptionPane.ERROR_MESSAGE);     
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try {
               //GET COONECTION
               
               
               Connection con=DriverManager.getConnection(conString, username, password);
              DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
              
               String fname=jTextField1.getText();
                String lname=jTextField2.getText();
                 String regNo=jTextField3.getText();
                 String key=regNo;
                  if(fname.length()==0 || lname.length()==0 || regNo.length()==0){
              JOptionPane.showMessageDialog(this, "PLEASE FILL ALL FIELDS", "Error", JOptionPane.ERROR_MESSAGE);
          }else{
                   if(jTable1.getSelectedRowCount()>0){  
              
                 
                
                 
                   String delete="delete from users where id="+key;
                
                 
                 String sql = "INSERT INTO users VALUES('" + fname + "','" +lname + "','" + regNo+ "')";
               Statement s = con.prepareStatement(sql);

            s.execute(sql);
            
             jTextField1.setText("");
               jTextField2.setText("");
                 jTextField3.setText("");
        JOptionPane.showMessageDialog(this, "DATA UPDATED SUCCESFULLY");
               }
               else{
                    JOptionPane.showMessageDialog(this, "SELECT THE ROW TO BE UPDATED AND CLICK ON UPDATE BUTTON ", "Error", JOptionPane.ERROR_MESSAGE);   
               }    
                  }
              

model.setRowCount(0);
show_Data();
               
        
           } catch (SQLException ex) {
               Logger.getLogger(JDBC_UI.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
model.setRowCount(0);
show_Data();
       
    }//GEN-LAST:event_jButton5ActionPerformed
    
   
    
      public void show_Data()
    {
      try{
        
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/users","root","");
          String select="select* from users";
          PreparedStatement st=con.prepareStatement(select);
          ResultSet rs=st.executeQuery();
          while(rs.next())
          {
              String fname=rs.getString("fname");
              String lname=rs.getString("lname");
              String regNo=rs.getString("regNo");
              
              DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
          String data[]={fname,lname,regNo};
          tbmodel.addRow(data);
          
          }}
          catch(Exception e)
                  {
                  e.printStackTrace();
                  }
    }
 
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDBC_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void alert(String there_is_nothing_to_update_) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  

    private void fetch() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class Crud {

        public Crud() {
        }
    }
}
